name: Deploy Hugo Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.161.1"
          extended: true

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Fix theme compatibility for Hugo v0.123+
        run: |
          # Fix .Site.Author deprecated usage in hello-friend-ng theme
          # Hugo v0.123+ changed .Site.Author from map to struct
          sed -i 's/{{ range .Site.Author }}{{ . }} {{ end }}/{{ site.Params.author.name }}/' themes/hello-friend-ng/layouts/partials/head.html
          sed -i 's/.Site.Author.email/site.Params.author.email/g' themes/hello-friend-ng/layouts/posts/rss.xml
          sed -i 's/$.Site.Author.name/site.Params.author.name/g' themes/hello-friend-ng/layouts/posts/rss.xml

      - name: Build the site
        run: hugo --minify --buildFuture

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
